# -*- coding: utf-8 -*-
"""GT-Project-SZA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s4ozQun3IZM4DbVcdCypJO0EBET6cDQ-
"""

pip install networkx matplotlib pyvis

import networkx as nx
import matplotlib.pyplot as plt

# --------------------------------------------------------
# 1. CREATE GRAPH
# --------------------------------------------------------
G = nx.Graph()

# Zones
ancient = ["R1","R2","R3","R4","R5","R6"]
caves = ["C1","C2","C3","C4","C5","C6","C7"]
shadow = ["S1","S2","S3","S4","S5","S6","S7"]

G.add_nodes_from(ancient)
G.add_nodes_from(caves)
G.add_nodes_from(shadow)

# Edges
edges = [
    # Ancient Halls
    ("R1","R2"),("R1","R3"),("R2","R3"),("R2","R4"),("R3","R5"),
    ("R5","R6"),("R4","R6"),("R3","R6"),("R4","C1"),

    # Crystal Caves
    ("C1","C2"),("C2","C3"),("C3","C4"),("C4","C5"),("C5","C6"),
    ("C6","C7"),("C1","C4"),("C3","C6"),("C5","S1"),("C7","R6"),

    # Shadow Fortress
    ("S1","S2"),("S2","S3"),("S3","S4"),("S4","S5"),("S5","S6"),
    ("S6","S7"),("S3","S6"),("S2","S7")
]

G.add_edges_from(edges)


# --------------------------------------------------------
# 2. NEAT MAIN GRAPH VISUALIZATION
# --------------------------------------------------------
plt.figure(figsize=(16, 12))

# Spread-out layout
pos = nx.kamada_kawai_layout(G)

# Coloring based on zones
node_colors = []
for n in G.nodes():
    if n in ancient:
        node_colors.append("#8ecae6")  # Light blue
    elif n in caves:
        node_colors.append("#d9ed92")  # Light green
    else:
        node_colors.append("#ffb4a2")  # Light red

nx.draw_networkx_edges(G, pos, width=2, edge_color="gray")
nx.draw_networkx_nodes(G, pos, node_size=900, node_color=node_colors)
nx.draw_networkx_labels(G, pos, font_size=10, font_weight="bold")

plt.title("Game Level Graph - The Lost Temple Network", fontsize=16)
plt.axis("off")
plt.show()


# --------------------------------------------------------
# 3. TEXT ANALYSIS OUTPUT
# --------------------------------------------------------
print("\n=============== GRAPH ANALYSIS ===============")
print("Total Rooms:", G.number_of_nodes())
print("Total Connections:", G.number_of_edges())

print("\nIs the map fully connected? →", nx.is_connected(G))

# Shortest path example
shortest = nx.shortest_path(G, "R1", "S5")
print("\nShortest Path (Entrance R1 → Throne Room S5):")
print(" → ".join(shortest))

# Eulerian Path
print("\nEulerian Path Possible? →", nx.is_eulerian(G))

# Hamiltonian approximation
def has_hamiltonian(G):
    return nx.is_connected(G)

print("Hamiltonian Path Likely? →", has_hamiltonian(G))


# --------------------------------------------------------
# 4. VISUALIZE SHORTEST PATH ONLY
# --------------------------------------------------------
plt.figure(figsize=(16, 12))

# Base graph gray
nx.draw(G, pos, node_color="lightgray", edge_color="lightgray",
        node_size=900, with_labels=False)

# Highlight shortest path in red
path_edges = list(zip(shortest, shortest[1:]))
nx.draw_networkx_nodes(G, pos, nodelist=shortest, node_color="#ff595e", node_size=950)
nx.draw_networkx_edges(G, pos, edgelist=path_edges, edge_color="red", width=3)

# Labels again
nx.draw_networkx_labels(G, pos, font_size=10, font_weight="bold")

plt.title("Highlighted Shortest Path: R1 → S5", fontsize=16)
plt.axis("off")
plt.show()